name: Deploy to Heroku

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.API_KEY}}  # Defined in the repository Settings > Secrets
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.APP_NAME }}
          usedocker: true
