# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Docker
      run: docker build . --file Dockerfile --tag ghactionservice:prod
      
   
    - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
      id: heroku
      uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
      with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.API_KEY }} # your  heroku api key
          app_name: ${{ secrets.APP_NAME }} # you aplication name
          dockerfile_path: '' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web
